# Generated by Django 3.2.13 on 2022-05-10 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=36)),
                ('api', models.CharField(help_text='API URL', max_length=1024)),
                ('headers', models.JSONField(null=True)),
                ('content_type', models.CharField(max_length=64)),
                ('body', models.JSONField(null=True)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('client_ip_address', models.CharField(max_length=50)),
                ('response', models.JSONField(null=True)),
                ('status_code', models.PositiveSmallIntegerField(help_text='Response status code')),
                ('result_code', models.PositiveSmallIntegerField(db_index=True, help_text='Result code', null=True)),
                ('retry_times', models.IntegerField(default=0)),
                ('execution_time', models.DecimalField(decimal_places=5, help_text='Server execution time (Not complete response time.)', max_digits=8)),
                ('added_on', models.DateTimeField(db_index=True)),
                ('request_user', models.ForeignKey(help_text='Request User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '接口日志',
                'verbose_name_plural': '接口日志',
                'db_table': 'drf_api_logs',
            },
        ),
    ]
