# Generated by Django 3.2.12 on 2022-04-18 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drf_api_logger', '0002_auto_20211221_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogsmodel',
            name='request_user',
            field=models.ForeignKey(help_text='Request User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apilogsmodel',
            name='result_code',
            field=models.PositiveSmallIntegerField(db_index=True, help_text='Result code', null=True),
        ),
        migrations.AddField(
            model_name='apilogsmodel',
            name='retry_times',
            field=models.IntegerField(default=0),
        ),
    ]
