# Generated by Django 3.1.7 on 2022-04-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0002_auto_20211221_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APILogsModel',
        ),
    ]
