# Generated by Django 5.2 on 2025-07-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0003_apilogsmodel_request_user_apilogsmodel_result_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILogsModel2',
            fields=[
            ],
            options={
                'verbose_name': 'API Log2',
                'verbose_name_plural': 'API Logs2',
                'managed': False,
                'proxy': True,
            },
            bases=('drf_api_logger.apilogsmodel',),
        ),
    ]
