# Generated by Django 3.2.12 on 2022-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0003_auto_20220418_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilogsmodel',
            name='headers',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='apilogsmodel',
            name='response',
            field=models.JSONField(),
        ),
    ]
