# Generated by Django 3.2.12 on 2022-04-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0004_auto_20220418_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilogsmodel',
            name='body',
            field=models.JSONField(),
        ),
    ]
