# Generated by Django 3.2.12 on 2022-04-19 02:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0005_auto_20220418_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilogsmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='apilogsmodel',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
