# Generated by Django 3.2.13 on 2022-04-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0007_alter_apilogsmodel_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilogsmodel',
            name='added_on',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='apilogsmodel',
            name='headers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='apilogsmodel',
            name='response',
            field=models.JSONField(null=True),
        ),
    ]
