# Generated by Django 3.2.13 on 2022-04-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0008_auto_20220419_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilogsmodel',
            options={'verbose_name': '接口日志', 'verbose_name_plural': '接口日志'},
        ),
    ]
