# Generated by Django 3.2.13 on 2022-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0009_alter_apilogsmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogsmodel',
            name='content_type',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
