# Generated by Django 3.2.13 on 2022-05-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_api_logger', '0010_apilogsmodel_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilogsmodel',
            name='request_id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
